### ISSUE TITLE
Patch 2.6 support

### ISSUE THREAD

**Issue by spg-stany** [dschu012/d2s#75]
d2s.bundle.min.js:1 Uncaught (in promise) Error: Save Bits is undefined for stat: 200:unused200 at position 14800
    at v (d2s.bundle.min.js:1:66083)
    at d2s.bundle.min.js:1:60920
    at d2s.bundle.min.js:1:54216
    at Object.next (d2s.bundle.min.js:1:54321)
    at d2s.bundle.min.js:1:53233
    at new Promise (<anonymous>)
    at i (d2s.bundle.min.js:1:52978)
    at _ (d2s.bundle.min.js:1:56527)
    at d2s.bundle.min.js:1:56021
    at d2s.bundle.min.js:1:54216

**Comment by dschu012** [comment]
please provide the save if you have one.

**Comment by spg-stany** [comment]
> please provide the save if you have one.
[Assassin2.6.d2s.zip](https://github.com/dschu012/d2s/files/10760948/Assassin2.6.d2s.zip)

**Comment by spg-stany** [comment]
error only when character use new runword items

**Comment by dschu012** [comment]
With the updated constants file the saves do load now. For some reason it doesnt show the name on the runewords :(.... Gonna close the issue since good enough for me.

![image](https://user-images.githubusercontent.com/1458109/219695261-ec2cae3a-9cd7-4f15-9a06-8880de09b88b.png)
